### ISSUE TITLE
Headshape

### ISSUE THREAD

**Issue by neurofractal** [tierneytim/OPM#2]
spm_opm_create should have an S.headshape input, in which headshape can be associated with fiducial info for better coregistration

**Comment by georgeoneill** [comment]
Hi @neurofractal 

I've got an experimental version of this working, and it looks like should work. But as you'll see we'll actually have to think about how we want to make this a permenant addtion.

Below are the anatomy/sensor coregistrations using 4 scenarios.

1. Subject anatomical - where canonical meshes are fitted with a non-linear warp.
2. Template anatomical - 7 DOF affine transformation (rigid body + gobal rescale) based only on the 3 fiducials.
3. Template + headshape - uses the headshape to do at 12 DOF affine transform (good if fiducials are not where one thinks they are) but then nixes the scaling after the fact. This is default behaviour for MEG data in SPM.
4. Template + headshape (EEG hack) - uses the full 12DOF affine transform. Default for EEG data in SPM

![image](https://user-images.githubusercontent.com/3579812/128214041-1561d929-d9cf-42ff-b078-3f69c8414907.png)

As you can see from a eyeball of these. If we use the default behaviour of SPM and it turns out the fiducials are close to where they *ideally* should be, its no better than just a bog standard template. But hacking the code to use an EEG-like behaviour looks promising! I'm just going to quantify the errors to see how much better it might be.

**Comment by neurofractal** [comment]
Thanks George - looks really promising. A couple of thoughts:
- One issue I'm finding is that the shape of the head from the ipad scan doesn't always match up with the shape of the canonical SPM template.. in particular the lower posterior part the head/neck. (I think this is because we are scanning people sitting up vs lying down as in an MRI scanner?) Perhaps this is why the very back of the cortical mesh is warped in a funny way for the bottom right picture??
- When 3D scanning with the ipad, we should ensure the person scans the ears so we can easily mark the fiducials

**Comment by georgeoneill** [comment]
Yeah I think as you'll see from the plot below your obervation about point one is correct, but I think its because that the canonical mesh cuts off not inferior to the brain enough for it to really minimse the issues. We definitely need to get the anatomical fiducial locations yes, 

The plot below is the difference in vertiex locations (Euclidian distance) between the non-linear warp to native space, and the other simplified fits, plotted in the same order as above.

Interestingly, even though from eyeballing fits 2 and 3 look similar above, it turns out using the headshape points gets the average error down a few millimeters. Using the EEG behvior (fit 4) looks like it should perform better, it does. **BUT** it does appear to get the variation in the error down. And becayse of the cutoff of the MRI in SPM its the infereior errors which have the largest error.

![image](https://user-images.githubusercontent.com/3579812/128219467-0c4df433-31ed-42c2-86c7-0beb42c52b94.png)

**Comment by neurofractal** [comment]
Interesting...

**Comment by georgeoneill** [comment]
Just some overlap plots, blue is the native, and red is the approximation, again in the order of the first post.

![image](https://user-images.githubusercontent.com/3579812/128222867-b2d011a8-bfdc-49f9-9e9e-c9255382cbf3.png)

**Comment by georgeoneill** [comment]
Just doing the lead field error (assume Nolte model). Just incase for some reason it turns out the way it warps the brain/csf boundary for the different approximations is somehow more important than just source position error...

**Comment by georgeoneill** [comment]
Measuring the relative error between the leadfields from the native MRI fit and the ximplifications. (norm of the difference of lead fields, scaled by norm of the native lead field). Option three (template + headshape MEG style) gives the lowest error based on SPM's way of dipole modelling.

![image](https://user-images.githubusercontent.com/3579812/128227139-e7c0d965-7d6d-4331-85c8-abfd218fb30a.png)

I think what this tells us is that the simple additional fitting based on the iPad generated headshape is the way to go. 

This is somwhat of a relief as to get the EEG method of headshape fitting on MEG data requires some hacking of how we communcated to SPM that this is OPM data - something we currently do not do. To get the MEG method working just requires changes to spm_opm_create. 

Thoughts?

**Comment by neurofractal** [comment]
Sounds good.. although I guess it's just the occipital cortex which is biasing the bottom right plot? I'll investigate which bits of the headshape to include/leave out...

Would you be able to share your code for calculating relative error between the leadfields? Then I can test my Thin Plate Spline (TPS) Warp approach...

**Comment by georgeoneill** [comment]
Yeah happy to share my code. Its a mess as I wrote it very quickly. But it should give you the ground work! 

https://gist.github.com/georgeoneill/e5407bca5321a438404953274cd0958e

**Comment by georgeoneill** [comment]
I'm going to consider this basic headshape implementaiton issue closed.
